backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/assets/img"
public_folder: "/assets/img"

collections:
  - name: "blog"
    label: "Entradas del Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - {
          label: "Fecha de publicación",
          name: "pubDate",
          widget: "datetime",
          format: "YYYY-MM-DD",
          date_format: "YYYY-MM-DD",
          time_format: false,
          picker_utc: false,
        }
      - { label: "Descripción", name: "description", widget: "text" }
      - {
          label: "Autor",
          name: "author",
          widget: "string",
          default: "Admin",
        }
      - label: "Imagen destacada"
        name: "image"
        widget: "object"
        required: false
        fields:
          - { label: "URL de la imagen", name: "url", widget: "image" }
          - {
              label: "Texto alternativo",
              name: "alt",
              widget: "string",
              default: "Imagen del artículo",
            }
      - {
          label: "Etiquetas",
          name: "tags",
          widget: "list",
          field: { label: "Etiqueta", name: "tag", widget: "string" },
          required: false,
        }
      - { label: "Contenido", name: "body", widget: "markdown" }
